server:
  port: 9998
spring:
  application:
    name: springcloud-user-hystrix-turbine
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
turbine:
  aggregator:
    clusterConfig: default
  appConfig: springcloud-user-consumer-ribbon-with-hystrix,springcloud-user-consumer-feign-with-hystrix
  clusterNameExpression: "'default'"