server:
  port: 9991
spring:
  application:
    name: springcloud-user-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
zuul:
  routes:
    hello:
      path: /myusers/**
      serviceId: springcloud-user-provider

ribbon:
  eureka:
    enabled: false
#servcieId
springcloud-user-provider:
  ribbon:
    listOfServers: http://localhost:8080,http://localhost:8081